# Generated by Django 4.0.4 on 2022-05-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bowl',
            fields=[
                ('cod_Bowl', models.IntegerField(primary_key=True, serialize=False, verbose_name='cod Bowl')),
                ('nom_Bowl', models.CharField(max_length=25, verbose_name='Nombre Bowl')),
                ('precio_Bowl', models.IntegerField(verbose_name='Precio Bowl')),
                ('descripcion_Bowl', models.CharField(max_length=50, verbose_name='descripcion Bowl')),
                ('cant_Bowl', models.IntegerField(verbose_name='Cantidad de Bowl')),
                ('estado_stock', models.CharField(max_length=10, verbose_name='Estado Bowl')),
            ],
        ),
    ]
