# Generated by Django 4.0.4 on 2022-05-05 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dressyoursalad', '0002_alter_bowl_cod_bowl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('cod_ped', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='cod pedido')),
                ('fecha_ped', models.CharField(max_length=25, verbose_name='Fecha pedido')),
                ('cantidad', models.CharField(max_length=25, verbose_name='Cantidad Bowl')),
                ('bowl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dressyoursalad.bowl')),
            ],
        ),
    ]
