# Generated by Django 4.0.4 on 2022-05-06 02:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressyoursalad', '0003_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_ped',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
