# Generated by Django 4.0.4 on 2022-05-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressyoursalad', '0004_alter_pedido_fecha_ped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cod_ped',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='cod pedido'),
        ),
    ]
