# Generated by Django 4.0.4 on 2022-05-10 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressyoursalad', '0007_pedido_pagado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cod_ped',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
