# Generated by Django 4.0.4 on 2022-05-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressyoursalad', '0011_pedido_boleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='precio',
            field=models.IntegerField(default=0, verbose_name='Precio'),
        ),
    ]
