# Generated by Django 4.0.4 on 2022-05-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressyoursalad', '0012_pedido_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='id_carrito',
            field=models.IntegerField(default=0, verbose_name='ID Carrito'),
        ),
    ]
